<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="testpackage" nsURI="testpackage" nsPrefix="testpackage">
  <eClassifiers xsi:type="ecore:EClass" name="NewEClass0" eSuperTypes="#//NewEClass5">
    <eOperations name="newEOperation3" lowerBound="4" upperBound="8"/>
    <eOperations name="newEOperation4" upperBound="3" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eOperations name="newEOperation12" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="NewEAttribute1" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newEAttribute2" lowerBound="8"
        upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newEAttribute11" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NewEClass5" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="TestOccurrences">
    <eOperations name="EOccurrenceZero" upperBound="0"/>
    <eOperations name="EOccurrenceZeroToOne"/>
    <eOperations name="EOccurrenceZeroToN" upperBound="7"/>
    <eOperations name="EOccurrenceZeroToUnbounded" upperBound="-1"/>
    <eOperations name="EOccurrenceOne" lowerBound="1"/>
    <eOperations name="EOccurrenceOneToN" lowerBound="1" upperBound="7"/>
    <eOperations name="EOccurrenceOneToUnbounded" lowerBound="1" upperBound="-1"/>
    <eOperations name="EOccurrenceN" lowerBound="5" upperBound="5"/>
    <eOperations name="EOccurrenceNToM" lowerBound="5" upperBound="10"/>
    <eOperations name="EOccurrenceNToUnbounded" lowerBound="5" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="EOccurrenceZero" upperBound="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="EOccurrenceZeroToOne"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="EOccurrenceZeroToN" upperBound="7"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="EOccurrenceZeroToUnbounded"
        upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="EOccurrenceOne" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="EOccurrenceOneToN" lowerBound="1"
        upperBound="7"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="EOccurrenceOneToUnbounded"
        lowerBound="1" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="EOccurrenceN" lowerBound="5"
        upperBound="5"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="EOccurrenceNToM" lowerBound="5"
        upperBound="9"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="EOccurrenceNToUnbounded"
        lowerBound="5" upperBound="-1"/>
  </eClassifiers>
</ecore:EPackage>
