<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Test" nsURI="testURI" nsPrefix="testPrefix">
  <eClassifiers xsi:type="ecore:EClass" name="Class">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference" eType="#//Abstract"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Abstract" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Interface" interface="true" eSuperTypes="#//Abstract">
    <eStructuralFeatures xsi:type="ecore:EReference" name="containment" eType="#//Class"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Enum"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DataType" instanceClassName="java.lang.Object"/>
</ecore:EPackage>
