<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="testNodesOnly" nsURI="testNodesOnly" nsPrefix="testNodesOnly">
  <eClassifiers xsi:type="ecore:EClass" name="Class"/>
  <eClassifiers xsi:type="ecore:EClass" name="Interface" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Abstract" abstract="true"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Enum"/>
</ecore:EPackage>
