<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="testpackage" nsURI="testpackage" nsPrefix="testpackage">
  <eClassifiers xsi:type="ecore:EClass" name="NewEClass0">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="NewEAttribute2">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NewEClass1" abstract="true"/>
</ecore:EPackage>
